name: mwe for mamba-org/setup-micromamba \#225

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

defaults:
  run:
    shell: bash -l {0}

jobs:
  run:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    env:
      OS: ${{ matrix.os }}
      PYTHON: ${{ matrix.py_ver }}
    steps:
    - uses: actions/checkout@master
    - uses: mamba-org/setup-micromamba@v1
      with:
        environment-file: environment.yaml
        create-args: >-
          python=3.12
        cache-environment: true